version: '3.9'
services:
  web:
    build: . 
    image: shop:latest 
    command: python app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis 
  redis:
    image: "redis:alpine"
    command: redis-server 
    ports:
      - "6379:6379"